#ifndef SWAY_CORE_FOUNDATION_TYPES_HPP
#define SWAY_CORE_FOUNDATION_TYPES_HPP

#include <sway/classpointermacros.hpp>
#include <sway/namespacemacros.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(core)
NAMESPACE_BEGIN(foundation)

DECLARE_CLASS_POINTER_TYPES(Context)
DECLARE_CLASS_POINTER_TYPES(Subsystem)
DECLARE_CLASS_POINTER_TYPES(Event)
DECLARE_CLASS_POINTER_TYPES(Eventable)
DECLARE_CLASS_POINTER_TYPES(EventHandler)

NAMESPACE_END(foundation)
NAMESPACE_END(core)
NAMESPACE_END(sway)

#endif  // SWAY_CORE_FOUNDATION_TYPES_HPP
