option(GLOB_THIRD_PARTY_DIR "Third party directory" OFF)
option(GLOB_EMSCRIPTEN_PLATFORM "Using emscripten compiler" OFF)
option(GLOB_EMSCRIPTEN_USE_BINDINGS "Using emscripten binding" OFF)
option(GLOB_EMSCRIPTEN_ENABLE_ASSERTIONS "" OFF)
option(GLOB_EMSCRIPTEN_ROOT_DIR "Emscripten root directory" OFF)
option(GLOB_BOOST_ROOT_DIR "Boost root directory" OFF)
option(GLOB_GTEST_ROOT_DIR "GTest root directory" OFF)
option(GLOB_GMOCK_ROOT_DIR "GMock root directory" OFF)
option(GLOB_GTEST_LIB_DIR "GTest libraries directory" OFF)
option(GLOB_GMOCK_LIB_DIR "GMock libraries directory" OFF)

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Choose the type of build" FORCE)
endif()
