#ifndef SWAY_DEFINES_HPP
#define SWAY_DEFINES_HPP

#define GLOB_DONT_CARE (-1)
#define GLOB_NULL 0

#define GLOB_IDX_INVALID GLOB_DONT_CARE
#define GLOB_IDX_INITIAL GLOB_NULL

#define GLOB_UID_INVALID GLOB_NULL
#define GLOB_UID_INITIAL 1

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#endif  // SWAY_DEFINES_HPP
