#ifndef SWAY_KEYWORDS_HPP
#define SWAY_KEYWORDS_HPP

#define MTHD_VIRTUAL(SIG) virtual SIG

#define PURE_VIRTUAL(SIG) MTHD_VIRTUAL(SIG) = 0

#define MTHD_OVERRIDE(SIG) SIG override

#define MTHD_VIRTUAL_OVERRIDE(SIG) virtual MTHD_OVERRIDE(SIG)

#define DTOR(OBJ) ~OBJ()

#define DTOR_DEFAULT(OBJ) DTOR(OBJ) = default

#define DTOR_VIRTUAL(OBJ) virtual DTOR(OBJ)

#define DTOR_VIRTUAL_DEFAULT(OBJ) virtual DTOR_DEFAULT(OBJ)

#endif  // SWAY_KEYWORDS_HPP
