macro(set_emscripten_compilation #[[ARG]] output_flags_arg 
                                 #[[ARG]] compilation_arg)
  if(${compilation_arg} STREQUAL "async")
    set(${output_flags_arg} "SHELL:-s WASM_ASYNC_COMPILATION=1")
  elseif(${compilation_arg} STREQUAL "sync")
    set(${output_flags_arg} "SHELL:-s WASM_ASYNC_COMPILATION=0")
  else()
    message(FATAL_ERROR "[EMSCRIPTEN]: Invalid compilation: ${compilation_arg}")
  endif()
endmacro(set_emscripten_compilation)
