function(custom_add_subdirectory SUBMODULE_NAME)
	if (NOT TARGET libmodule_${SUBMODULE_NAME})
		add_subdirectory(submodules/sway.module_${SUBMODULE_NAME})
	endif()
endfunction(custom_add_subdirectory)
